version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/fullstack"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
 
