version: '3'
services:
  mysql:
    build: ./database/mysql
    volumes:
      - ./database/mysql/data/mysql:/var/lib/mysql
      - ./database/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
    network_mode: host

  backend:
    build: ./backend
    volumes:
      - ./database/mysql/data/image:/root/website/database/mysql/data/image
    restart: always
    tty: true
    network_mode: host
    depends_on:
      - mysql
  frontend:
    build: ./frontend
    volumes:
      - ./database/mysql/data/image:/root/website/database/mysql/data/image
      - ./frontend/build:/root/website/frontend/build
    network_mode: host
    depends_on:
      - backend
  nginx:
    build: ./nginx
    volumes:
      - ./database/mysql/data/image:/root/website/database/mysql/data/image
      - ./frontend/build:/root/website/frontend/build
    restart: always
    network_mode: host
    depends_on:
      - frontend

