version: '3'
services:
  mysql:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - blog

  golang:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - /root/blog/backend/image:/root/blog/backend/image
    restart: always
    tty: true
    networks:
      - blog
    depends_on:
      - mysql


  nginx:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - /root/blog/backend/image:/root/blog/backend/image
    networks:
      - blog
    depends_on:
      - golang

networks:
  blog:
    driver: bridge
    external: true
