services:
  mysql:
    build: mysql
    volumes:
      - ./mysql/data/mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_CHARSET=utf8mb4
    restart: always
    network_mode: host
    
  redis:
    build: redis
    restart: always
    network_mode: host
    depends_on:
      - mysql

  web:
    build: web
    volumes:
      - ./mysql/data/image:/root/website/mysql/data/image
      - ./web:/root/website/web
    restart: always
    network_mode: host
    depends_on:
      - mysql
      - redis
      
  nginx:
    build: nginx
    volumes:
      - ./mysql/data/image:/root/website/mysql/data/image
    restart: always
    network_mode: host
    depends_on:
      - web

