mysql:
  # host: 172.20.0.2
  host: 127.0.0.1
  port: 3306
  db: blog
  user: root
  password: 123456
  log_level: dev

logger:
  level: info
  prefix: '[blg]'
  director: log
  show_line: true
  log_in_console: true

system:
  host: "127.0.0.1"
  port: 8080
  env: release
  directory: "/home/linzui/Code/blog/backend/"  #项目目录 署在服务器时修改项目目录
  # router: "http://172.20.0.4/image/"        #静态图片路由 部署在服务器时修改IP 不用添加端口
  router: "http://127.0.0.1:8080/image/"
