[package]
name = "webhook"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.7.0"
hmac = "0.13.0-pre.3"
hex = "0.4.3"
sha2 = "0.11.0-pre.3"
regex = "1.10.5"
lazy_static = "1.4.0"
serde_json = "1.0.117"
