mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: website
  user: root
  password: 123456
  log_level: dev

redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0

logger:
  level: info
  prefix: '[WEB]'
  director: log
  show_line: true
  log_in_console: true

system:
  host: 0.0.0.0
  port: 8080
  env: release
  directory: ../database/mysql/data/image/
  smtp_email: yangminghe20@gmail.com
  smtp_password: [FILTERED]
  smtp_host: smtp.gmail.com
  smtp_port: 587
